apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: rpi-k8s-pods-indicator
  name: rpi-k8s-pods-indicator-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: rpi-k8s-pods-indicator
  labels:
    app: rpi-k8s-pods-indicator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: rpi-k8s-pods-indicator-sa
  namespace: kube-system
